version: "3"
services:

  mariadb:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: voloroot
      MYSQL_DATABASE: volo
      MYSQL_USER: volouser
      MYSQL_PASSWORD: volouser
    networks:
      - backend
    restart: on-failure
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - backend

networks:     
  backend:
    driver: bridge

volumes:
  mariadb_data:
    driver: local