version: "3"
services:

  mariadb:
    image: mariadb:10.4
    container_name: volo-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: voloroot
      MYSQL_DATABASE: volo
      MYSQL_USER: volouser
      MYSQL_PASSWORD: volouser
    networks:
      - backend
    restart: on-failure
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: volo-adminer 
    restart: always
    ports:
      - 8080:8080
    networks:
      - backend

  redis:
    image: redis
    container_name: volo-redis 
    ports:
      - 6379:6379
    networks:
      - backend
    volumes: 
      - redis_data:/data

networks:     
  backend:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
  redis_data:
    driver: local